### ISSUE TITLE
JS # in routing / URL

### ISSUE THREAD

**Issue by ACPK** [manukall/phoenix_token_auth_react#3]
Any chance you could have the routes remove the # in the URL and have it work for page refreshes?

**Comment by manukall** [comment]
Yes, react-router has an option for that. In https://github.com/manukall/phoenix_token_auth_react/blob/master/web/static/js/stores/router_store.jsx#L15 just remove the comment, so that it reads `location: Router.HistoryLocation`

**Comment by ACPK** [comment]
@manukall Doesn't seem to work for user confirmations and password resets  in this sample app. It also doesn't work on Heroku.
