### ISSUE TITLE
README should indicate need to change email_sender config value

### ISSUE THREAD

**Issue by grempe** [manukall/phoenix_token_auth_react#4]
On a new clone I was unable to send emails until I found and also changed the config value in config/config.exs from :

```
email_sender: "coolapp@example.com"
```

to something appropriate for my domain.  Until I did so I would see this in the logs, indicating apparent success, but mailgun would apparently not actually deliver it:

```
[info] Sent welcome email to SOME_EMAIL
```

Also, the README should make clear that the Elixir mailgun client is using the mailgun HTTP API, not the SMTP server, so the credentials used should reflect that.  Those coming from Rails, used to sending mail via SMTP, might be tripped up by this.

Thanks for the great example code.

**Comment by grempe** [comment]
Added pull request to fix this issue and also upgrade two Phoenix versions.

https://github.com/manukall/phoenix_token_auth_react/pull/5

**Comment by manukall** [comment]
I merged your pull request. Thanks very much!
