### ISSUE TITLE
New Poison dependency version for phoenix_token_auth prevents upgrade of this demo to Phoenix 0.13.0

### ISSUE THREAD

**Issue by grempe** [manukall/phoenix_token_auth_react#6]
I am doing a version by version upgrade of this demo app to Phoenix 0.13.0 (which I am submitting in pull requests to you soon) but I can't do the upgrade from 0.12.0 to 0.13.0.  The problem is that you bumped the version requirement for Poison to ~> 1.4.0 and both hound and mailgun which are required for this app need ~> 1.3.0.

```
~/src/phoenix_token_auth_react (master ✗)$ mix deps.get
Running dependency resolution
Looking up alternatives for conflicting requirements on poison
  Activated version: 1.3.1
  From phoenix_token_auth v0.0.8: ~> 1.4.0
  From hound v0.6.0: ~> 1.3.0
  From deps/mailgun/mix.exs: ~> 1.3.1
** (Mix) Hex dependency resolution failed, relax the version requirements or unlock dependencies
```

You seem to have upgraded the version requirement in the other repository in this commit: 022193c8f16e8842c875be17ec88701dc3ea26d5

Its not clear to me on a quick look why.  Can you see about relaxing the new requirement to allow >= 1.3.0 and pushing a new version?

**Comment by manukall** [comment]
Just released a new version of phoenix_token_auth with relaxed poison requirement.

I guess this will break at some point, but at the moment everything moves so fast that we really can't expect all dependencies to stay up to date.

Thanks for working on this!

**Comment by grempe** [comment]
I have a pull request open again on phoenix_token_auth which resolves some issues.

I just opened a pull request on this repo with an upgrade to Phoenix 0.13.0. You should be able to close this issue when (another) new phoenix_token_auth is released and when the following pull request is merged:

https://github.com/manukall/phoenix_token_auth_react/pull/7

Cheers,

Glenn

**Comment by manukall** [comment]
hey @grempe, i just published a new phoenix_token_auth release. Thanks for contributing!!!!
