### ISSUE TITLE
PhoenixTokenAuthReact.Endpoint terminated

### ISSUE THREAD

**Issue by ACPK** [manukall/phoenix_token_auth_react#9]
[error] #PID<0.379.0> running PhoenixTokenAuthReact.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /api/v1/users
*\* (exit) an exception was raised:
    *\* (MatchError) no match of right hand side value: {:error, 401, "Forbidden"}
        lib/phoenix_token_auth/mailer.ex:33: PhoenixTokenAuth.Mailer.send_welcome_email/2
        lib/ecto/adapters/sql.ex:442: Ecto.Adapters.SQL.transaction/3
        lib/phoenix_token_auth/users_controller.ex:29: PhoenixTokenAuth.UsersController.create/2
        lib/phoenix_token_auth/users_controller.ex:1: PhoenixTokenAuth.UsersController.phoenix_controller_pipeline/2
        (phoenix_token_auth_react) lib/phoenix/router.ex:297: PhoenixTokenAuthReact.Router.dispatch/2
        (phoenix_token_auth_react) lib/phoenix/router.ex:2: PhoenixTokenAuthReact.Router.call/2
        (phoenix_token_auth_react) lib/phoenix_token_auth_react/endpoint.ex:1: PhoenixTokenAuthReact.Endpoint.phoenix_endpoint_pipeline/1
        (phoenix_token_auth_react) lib/plug/debugger.ex:90: PhoenixTokenAuthReact.Endpoint."call (overridable 3)"/2

**Comment by manukall** [comment]
hey,
this looks like an authentication problem with mailgun.

**Comment by ACPK** [comment]
Any suggestions as it's weird because I had your app working awhile back? I can share my test repo with you if that's ok.

**Comment by manukall** [comment]
i get the exact same error when i use a wrong mailgun key. didi you maybe forget to export some env variable or change your key at mailgun?
